#!/bin/bash -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH

payload=/tmp/grafana-dashboard-request

cat > $payload <&0

url=$(jq -r '.source.url // ""' < $payload)
token=$(jq -r '.source.token // ""' < $payload)

echo Curl dashboards
dashboards=$(curl -s -H "Authorization: Bearer $token" -H 'Content-Type: application/json' $url/api/search?tag=sync | jq -r '.[] | .uri')
responses='{}'

for uri in $dashboards; do
  echo Curl dashboard: $uri
  response=$(curl -s -H "Authorization: Bearer $token" -H 'Content-Type: application/json' $url/api/dashboards/$uri | jq -r '{ (.dashboard.title): .dashboard.version|tostring }')
  responses=$(echo "$responses" | jq ".+ $response")
done

echo "$responses" | jq '[.]' >&3
